# use the latest ubuntu environment (18.04) available on travis
dist: bionic

language: go


# Only clone the most recent commit.
git:
  depth: 1


# Don't email me the results of the test runs.
notifications:
  email: false

# Test files only in root
script: go test -timeout 30s .
 