# use the latest ubuntu environment (18.04) available on travis
dist: windows

language: go

env: GO111MODULE=on GOFLAGS='-mod vendor'

go:
  - 1.13.x

# Only clone the most recent commit.
git:
  depth: 1

# Skip install
install: false

# Don't email me the results of the test runs.
notifications:
  email: false

# Test files only in root
script: go test -timeout 30s .
 